version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${EXTERNAL_FOLDER}/nginx/cache/:/etc/nginx/cache
      - /etc/ssl_certs/:/etc/ssl_certs/
    ports:
      - 80:80
      - 443:443
